apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deploy
  namespace: app-dev
  labels:
    app: dev-app
  annotations:
spec:
  selector:
    matchLabels:
      app: dev-app
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: dev-app
    spec:
      containers:
      - name: dev-app
        image: aimvector/python:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: config-volume
          mountPath: /configs/
      volumes:
      - name: config-volume
        configMap:
          name: app-dev-config
