apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: app-dev
  labels:
    app: service-dev-app
spec:
  type: LoadBalancer
  selector:
    app: dev-app
  # externalIPs: ["127.0.0.1"]
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 5000
