name: Composite Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    
jobs:
    composite_workflow:
      runs-on: ubuntu-latest
      
      steps:
      - name: Checkout code
        uses: actions/checkout@v4
  
      - name: Use My Composite Action
        uses: ./gh_custom_actions/
        with:
            Name: 'Alice'
            Sensitive: ${{ secrets.Sensitive_IP }}
  