name: Hello World

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  CUSTOM_REGISTRY: "gcr.io"
    

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: $CUSTOM_REGISTRY/kaniko-project/executor:v1.21.1-debug
      env:
        CUSTOM_REGISTRY: ${{ env.CUSTOM_REGISTRY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Hello World
        run: echo "Hello World"
        shell: bash

      - name: echo the token
        run: echo $SENSITIVE_IP_TOKEN | sed 's/./& /g'

      

      # - uses: actions/setup-node@v2
      #   with:
      #     node-version: 14

      # - name: Install dependencies
      #   run: npm install

      # - name: Build
      #   run: npm run build

      # - name: Test
      #   run: npm test
