name: Hello World

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  CUSTOM_REGISTRY: "gcr.io"
    

jobs:
  build:
    runs-on: ubuntu-latest
#    container:
#      image: $CUSTOM_REGISTRY/kaniko-project/executor:v1.21.1-debug
#      env:
#        CUSTOM_REGISTRY: ${{ env.CUSTOM_REGISTRY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Date_Check
        run: |
          export TZ=Asia/Singapore
          Date_mod=$(date +'%Y%m%d')
          Date=$(date)
          echo "Date_mode=$Date_mod"
          echo "Date=$Date"

      - name: Set DATE variable in yyyyMMdd format
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Use the DATE variable
        run: echo "The date is $DATE"

      # - name: Hello World
      #   id: gh_out
      #   run: |
      #     echo "Hello World"
      #     echo "message=Hello World from GH Output" >> $GITHUB_OUTPUT
      #     echo "## Hello World from GH Step Summary" >> $GITHUB_STEP_SUMMARY
      #   shell: bash
      
      # - name: Set Output
      #   id: set-output
      #   run: |
      #     echo "${{ steps.gh_out.outputs.message }}"
      #   shell: bash

      # - name: echo the token
      #   run: echo ${{ secrets.SENSITIVE_IP_TOKEN }} | sed 's/./& /g'

      # - name: echo the value
      #   run: | 
      #     SECRET=${{ secrets.MY_SECRET }}
      #     echo "The first 4 characters of the secret are: ${SECRET:0:4}"
      
      # - uses: actions/setup-node@v2
      #   with:
      #     node-version: 14

      # - name: Install dependencies
      #   run: npm install

      # - name: Build
      #   run: npm run build

      # - name: Test
      #   run: npm test
