name: Hello World

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  CUSTOM_REGISTRY: "registry.hub.docker.com"
    

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ${{ env.CUSTOM_REGISTRY }}/node:14
      # env:
      #   CUSTOM_REGISTRY: ${{ env.CUSTOM_REGISTRY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Hello World
        run: echo "Hello World"
        shell: bash

      - name: echo the variables.container_image
        run: echo ${{ env.CUSTOM_REGISTRY }}

      

      # - uses: actions/setup-node@v2
      #   with:
      #     node-version: 14

      # - name: Install dependencies
      #   run: npm install

      # - name: Build
      #   run: npm run build

      # - name: Test
      #   run: npm test
